#!/usr/bin/env python3
"""
Compare unified findings against a JSON baseline and write a Markdown summary.

No database: `known_issues.json` is the source of truth for accepted/tracked
fingerprints. New findings are those present in the scan but not in the baseline.
Resolved findings are baseline entries that no longer appear in the scan.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class BaselineIssue:
    fingerprint: str
    note: str


def load_baseline(path: Path) -> tuple[dict[str, BaselineIssue], list[str]]:
    """
    Baseline file format:
    {
      "issues": [
        { "fingerprint": "bandit:B301:file.py:10", "note": "accepted for demo" }
      ]
    }
    """
    if not path.is_file():
        return {}, []

    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON in baseline {path}: {exc}") from exc

    issues_raw = data.get("issues")
    if issues_raw is None:
        # Allow a minimal file for first-time setup.
        return {}, []

    if not isinstance(issues_raw, list):
        raise SystemExit(f"Baseline `issues` must be a list in {path}")

    by_fp: dict[str, BaselineIssue] = {}
    order: list[str] = []
    for item in issues_raw:
        if not isinstance(item, dict):
            continue
        fp = str(item.get("fingerprint") or "").strip()
        if not fp:
            continue
        note = str(item.get("note") or "").strip()
        by_fp[fp] = BaselineIssue(fingerprint=fp, note=note)
        order.append(fp)
    return by_fp, order


def load_findings(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []
    if not isinstance(data, list):
        return []
    return [x for x in data if isinstance(x, dict)]


def severity_rank(sev: str) -> int:
    order = {"critical": 4, "high": 3, "medium": 2, "low": 1, "info": 0}
    return order.get((sev or "").lower(), 0)


def render_report(
    findings: list[dict[str, Any]],
    baseline: dict[str, BaselineIssue],
    baseline_order: list[str],
) -> str:
    fps_in_scan = {str(f.get("fingerprint") or "") for f in findings if f.get("fingerprint")}

    new_findings = [f for f in findings if str(f.get("fingerprint") or "") not in baseline]
    existing = [f for f in findings if str(f.get("fingerprint") or "") in baseline]

    # Preserve baseline file order, then any extra keys (hand-edited JSON).
    ordered_fps = list(dict.fromkeys([fp for fp in baseline_order if fp] + list(baseline.keys())))
    resolved_fps = [fp for fp in ordered_fps if fp in baseline and fp not in fps_in_scan]

    new_findings.sort(key=lambda f: severity_rank(str(f.get("severity") or "")), reverse=True)
    existing.sort(key=lambda f: severity_rank(str(f.get("severity") or "")), reverse=True)

    lines: list[str] = []
    lines.append("# Vulnerability summary")
    lines.append("")
    lines.append("Generated by `scripts/vuln_tracker.py` from unified scan output.")
    lines.append("")
    lines.append("## Counts")
    lines.append("")
    lines.append(f"- **New:** {len(new_findings)}")
    lines.append(f"- **Existing (in baseline):** {len(existing)}")
    lines.append(f"- **Resolved (was in baseline, not in latest scan):** {len(resolved_fps)}")
    lines.append("")

    def table_for(rows: list[dict[str, Any]], status: str, *, show_baseline_note: bool) -> None:
        lines.append("| Status | Tool | Severity | Title | Location | Recommendation |")
        lines.append("|---|---|---|---|---|---|")
        for f in rows:
            fp = str(f.get("fingerprint") or "")
            note = baseline[fp].note if show_baseline_note and fp in baseline else ""
            title = str(f.get("title") or "").replace("|", "\\|")
            loc = str(f.get("location") or "").replace("|", "\\|")
            rec = str(f.get("recommendation") or "").replace("|", "\\|")
            if note:
                rec = f"{rec} *(baseline note: {note})*".replace("|", "\\|")
            lines.append(
                "| "
                + " | ".join(
                    [
                        status,
                        str(f.get("tool") or ""),
                        str(f.get("severity") or ""),
                        title,
                        loc,
                        rec,
                    ]
                )
                + " |"
            )
        lines.append("")

    lines.append("## New findings")
    lines.append("")
    if not new_findings:
        lines.append("_None — all current fingerprints are listed in `known_issues.json` or scan is clean._")
        lines.append("")
    else:
        table_for(new_findings, "new", show_baseline_note=False)

    lines.append("## Existing findings (acknowledged in baseline)")
    lines.append("")
    if not existing:
        lines.append("_None._")
        lines.append("")
    else:
        table_for(existing, "existing", show_baseline_note=True)

    lines.append("## Resolved (removed from scan output)")
    lines.append("")
    if not resolved_fps:
        lines.append("_None._")
        lines.append("")
    else:
        lines.append("These fingerprints were in `known_issues.json` but did not appear in the latest unified report.")
        lines.append("")
        for fp in resolved_fps:
            note = baseline[fp].note if fp in baseline else ""
            lines.append(f"- `{fp}`" + (f" — {note}" if note else ""))
        lines.append("")

    lines.append("## How to update the baseline")
    lines.append("")
    lines.append(
        "After you fix a true positive, re-run the pipeline; the fingerprint should disappear "
        "and move to **Resolved**. To formally accept risk, add an object to `issues` in "
        "`known_issues.json` with the exact `fingerprint` from the unified JSON "
        "(field `fingerprint`)."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Diff unified findings vs baseline; write Markdown report.")
    parser.add_argument("--findings", type=Path, required=True, help="Unified findings JSON (list)")
    parser.add_argument("--baseline", type=Path, default=Path("known_issues.json"), help="Baseline JSON path")
    parser.add_argument("-o", "--output", type=Path, default=Path("reports/vuln_report.md"), help="Markdown output")
    parser.add_argument(
        "--fail-on-new",
        action="store_true",
        help="Exit with code 1 if any finding is classified as new",
    )
    args = parser.parse_args()

    baseline, order = load_baseline(args.baseline)
    findings = load_findings(args.findings)

    report = render_report(findings, baseline, order)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"Wrote report to {args.output}")

    if args.fail_on_new:
        fps_baseline = set(baseline.keys())
        new_count = sum(1 for f in findings if str(f.get("fingerprint") or "") not in fps_baseline)
        if new_count:
            print(f"ERROR: {new_count} new finding(s) not in baseline.", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
